### ISSUE TITLE
SAX + HopperOptimizations seems to break mixin.chunk.palette

### ISSUE THREAD

**Issue by jtenner** [Hephaestus-Dev/SAX#14]
Hey! Love this plugin. I use it on my server and it encourages my players to avoid cheating.

Currently, it works perfectly as intended with the latest version of lithium. However, when I apply 2no2name's hopper optimizations, I yield the following error:

```
[16:59:18] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking memory connection
	at net.minecraft.class_3242.method_14357(class_3242.java:176) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:882) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:91) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.ClassCastException: class me.jellysquid.mods.lithium.common.world.chunk.LithiumHashPalette cannot be cast to class dev.hephaestus.fiblib.impl.Fixable (me.jellysquid.mods.lithium.common.world.chunk.LithiumHashPalette and dev.hephaestus.fiblib.impl.Fixable are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @28cda624)
	at net.minecraft.class_2841.fix(class_2841.java:2016) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_2826.fix(class_2826.java:1019) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_2672.handler$zlk000$fixDataSize(class_2672.java:532) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_2672.method_11522(class_2672.java) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_2672.<init>(class_2672.java:58) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_3898.method_18715(class_3898.java:1091) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_3898.method_17241(class_3898.java:779) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_3898.method_18714(class_3898.java:902) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_3898.method_18701(class_3898.java:1024) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_3215.method_18755(class_3215.java:477) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_3218.method_18778(class_3218.java:933) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_3218.method_18771(class_3218.java:819) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_3218.method_18213(class_3218.java:798) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:224) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_3248.method_14384(class_3248.java:113) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_3248.redirect$zkd000$handlePlayerJoin(class_3248.java:562) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_3248.method_18785(class_3248.java:65) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:228) ~[intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:173) ~[intermediary-minecraft-1.16.5-client.jar:?]
	... 6 more
[16:59:18] [Server thread/ERROR]: This crash report has been saved to: C:\Users\Joshua Tenner\Desktop\MultiMC\instances\1.16.51\.minecraft\crash-reports\crash-2021-03-22_16.59.18-server.txt
[16:59:18] [Server thread/INFO]: Stopping server
[16:59:18] [Server thread/INFO]: Saving players
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 3/22/21, 4:59 PM
Description: Ticking memory connection

java.lang.ClassCastException: class me.jellysquid.mods.lithium.common.world.chunk.LithiumHashPalette cannot be cast to class dev.hephaestus.fiblib.impl.Fixable (me.jellysquid.mods.lithium.common.world.chunk.LithiumHashPalette and dev.hephaestus.fiblib.impl.Fixable are in unnamed module of loader net.fabricmc.loader.launch.knot.KnotClassLoader @28cda624)
	at net.minecraft.class_2841.fix(class_2841.java:2016)
	at net.minecraft.class_2826.fix(class_2826.java:1019)
	at net.minecraft.class_2672.handler$zlk000$fixDataSize(class_2672.java:532)
	at net.minecraft.class_2672.method_11522(class_2672.java)
	at net.minecraft.class_2672.<init>(class_2672.java:58)
	at net.minecraft.class_3898.method_18715(class_3898.java:1091)
	at net.minecraft.class_3898.method_17241(class_3898.java:779)
	at net.minecraft.class_3898.method_18714(class_3898.java:902)
	at net.minecraft.class_3898.method_18701(class_3898.java:1024)
	at net.minecraft.class_3215.method_18755(class_3215.java:477)
	at net.minecraft.class_3218.method_18778(class_3218.java:933)
	at net.minecraft.class_3218.method_18771(class_3218.java:819)
	at net.minecraft.class_3218.method_18213(class_3218.java:798)
	at net.minecraft.class_3324.method_14570(class_3324.java:224)
	at net.minecraft.class_3248.method_14384(class_3248.java:113)
	at net.minecraft.class_3248.redirect$zkd000$handlePlayerJoin(class_3248.java:562)
	at net.minecraft.class_3248.method_18785(class_3248.java:65)
	at net.minecraft.class_2535.method_10754(class_2535.java:228)
	at net.minecraft.class_3242.method_14357(class_3242.java:173)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:882)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:832)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 15.0.2, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
	Memory: 54230312 bytes (51 MB) / 1042284544 bytes (994 MB) up to 1073741824 bytes (1024 MB)
	CPUs: 4
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
	Fabric Mods: 
		fabric: Fabric API 0.32.5+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+dc716ea17d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+351679a77d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.5+351679a77d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.3
		fiblib: FibLib 1.0.1
		hopperoptimizations: Hopper Optimizations 0.3.6
		hopperoptimizations-lithium: Lithium 0.6.4
		java: OpenJDK 64-Bit Server VM 15
		minecraft: Minecraft 1.16.5
		sax: Simple Anti X-Ray 1.0.1
	Player Count: 1 / 8; [class_3222['devilmint'/432, l='ServerLevel[New World]', x=-251.50, y=66.00, z=-127.50]]
	Data Packs: vanilla, Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Joshua Tenner\Desktop\MultiMC\instances\1.16.51\.minecraft\crash-reports\crash-2021-03-22_16.59.18-server.txt
2021-03-22 16:59:18,745 Server thread WARN Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger
```

Current workaround is modify the lithium config:

```
mixin.chunk.palette=false
```

Not sure if there's much I can do, but I am a moderate java dev. 

Also, this is the jar file I used to recreate the issue: https://github.com/2No2Name/hopperOptimizations/releases/tag/0.3.6

Make sure to download hopper opts and the lithium fork used for this.

**Comment by Haven-King** [comment]
The problem is that 2No2Name's Lithium fork uses the modid `hopperoptimizations-lithium` instead of just `lithium`, which means my mixin isn't applied, since [I check specifically if Lithium's present](https://github.com/Haven-King/FibLib/blob/586f7b2b3d280e446d74cb82951d584afb460981/src/main/java/dev/hephaestus/fiblib/mixin/VolatileMixinPlugin.java#L25). I can probably check if the class itself is present instead so that it works with their fork.

**Comment by Haven-King** [comment]
You can download the updated version from either [Modrinth ](https://modrinth.com/mod/sax/version/uKjtpldv)or [CurseForge](https://www.curseforge.com/minecraft/mc-mods/simple-anti-x-ray/files/3248410)!
