### ISSUE TITLE
Mixin DeObfuscateTargetedBlock apply failed

### ISSUE THREAD

**Issue by LordCandyAndy** [Hephaestus-Dev/SAX#4]
Running fabric 20w49a server

```
[17:54:58] [main/INFO]: Loading for game Minecraft 20w49a
[17:54:58] [ForkJoinPool-1-worker-1/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[17:54:59] [main/WARN]: Warnings were found! 
 - Mod 'ViaFabric' (viafabric) conflicts with any version of mod 'Fabric Registry Sync (v0)' (fabric-registry-sync-v0), but a matching version is present: 0.7.3+d591fc0a6c!
	 - While this won't prevent you from starting the game, the developer(s) of 'ViaFabric' (viafabric) have found that version 0.7.3+d591fc0a6c of 'Fabric Registry Sync (v0)' (fabric-registry-sync-v0) conflicts with their mod.
	 - It is heavily recommended to remove one of the mods.
	 - Mod 'Fabric Registry Sync (v0)' (fabric-registry-sync-v0) v0.7.3+d591fc0a6c is being provided by 'Fabric API' (fabric) v0.7.3+d591fc0a6c.
 - Mod 'ViaBackwards' (viabackwards) recommends any version of mod viarewind, which is missing!
	 - You must install any version of viarewind.
[17:54:59] [main/INFO]: [FabricLoader] Loading 62 mods: fabric-renderer-api-v1@0.3.4+e1f1abb16c, fabric-keybindings-v0@0.2.0+9f7a74236c, viafabric@0.2.16-SNAPSHOT+build-608.1-mc-1.16, fabricloader@0.10.8, fabric-structure-api-v1@1.1.2+cc3cc6c66c, fabric-containers-v0@0.1.9+bee3a8866c, fabric-dimensions-v1@2.0.2+e1f1abb16c, fabric-object-builder-api-v1@1.10.2+9f7a74236c, cotton-client-commands@1.0.1+1.16-rc1, paxi@20w45a-1.0, fabric-game-rule-api-v1@1.0.4+3e817a626c, fabric-api-base@0.2.0+eaafab806c, fabric-rendering-data-attachment-v1@0.1.4+9f7a74236c, fiblib@0.1.5-1.16.2, fabric-textures-v0@1.0.5+9f7a74236c, player_events_api@2.0.0, fabric-rendering-fluids-v1@0.1.12+9f7a74236c, fabric-blockrenderlayer-v1@1.1.4+9f7a74236c, fabric-lifecycle-events-v1@1.4.0+8f5b7a466c, fabric-renderer-registries-v1@3.0.3+0c3d83a56c, fabric-loot-tables-v1@1.0.3+0c3d83a56c, fabric@0.28.1+1.17, carpet@1.4.20, fabric-particles-v1@0.2.2+9f7a74236c, viaversion@3.3.0-20w49a, fabric-networking-v0@0.3.0+bee3a8866c, fabric-networking-blockentity-v0@0.2.7+bee3a8866c, fabricproxy@1.3.3, minecraft@1.17-alpha.20.49.a, fabric-screen-handler-api-v1@1.1.3+9f7a74236c, viabackwards@3.3.0-20w49a, serversimplified@1.1.2, fabric-command-api-v1@1.0.9+9f7a74236c, ban-trigger@1.1.0, fabric-tool-attribute-api-v1@1.2.7+9f7a74236c, fabric-renderer-indigo@0.4.5+e1f1abb16c, fabric-events-interaction-v0@0.4.3+9f7a74236c, fabric-crash-report-info-v1@0.1.2+b7f9825d6c, fabric-item-api-v1@1.2.1+9f7a74236c, spark@1.4.3, player_events@2.0.0, fabric-rendering-v0@1.1.1+9f7a74236c, fabric-key-binding-api-v1@1.0.1+730711c66c, fabric-rendering-v1@1.3.1+9f7a74236c, autoconfig1u@2.2.0, fabric-resource-loader-v0@0.3.5+e1f1abb16c, mclogs@1.0.0, carpet-tis-addition@1.11.1, fabric-content-registries-v0@0.2.0+880269e66c, fabric-tag-extensions-v0@1.1.1+e1f1abb16c, fabric-biome-api-v1@3.1.0+f1dfa4ca6c, sax@0.2.0, fabric-commands-v0@0.2.0+9f7a74236c, fabric-registry-sync-v0@0.7.3+d591fc0a6c, fabric-mining-levels-v0@0.1.2+9f7a74236c, fabric-networking-api-v1@1.0.0+fd1187376c, fabric-events-lifecycle-v0@0.2.0+9f7a74236c, fabric-models-v0@0.1.1+9f7a74236c, fabric-item-groups-v0@0.2.1+9f7a74236c, fabric-object-builders-v0@0.7.2+9f7a74236c, mixintrace@1.0.0, org_yaml_snakeyaml@1.26
[17:54:59] [main/WARN]: Mod `paxi` (20w45a-1.0) does not respect SemVer - comparison support is limited.
[17:54:59] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/data/andy/Test/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[17:55:06] [main/FATAL]: Mixin apply failed sax.mixins.json:server.DeObfuscateTargetedBlock -> net.minecraft.class_3222: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Invalid descriptor on sax.mixins.json:server.DeObfuscateTargetedBlock->@Inject::initializeDeObfuscator(Lnet/minecraft/server/MinecraftServer;Lnet/minecraft/class_3218;Lcom/mojang/authlib/GameProfile;Lnet/minecraft/class_3225;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V! Expected (Lnet/minecraft/server/MinecraftServer;Lnet/minecraft/class_3218;Lcom/mojang/authlib/GameProfile;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (Lnet/minecraft/server/MinecraftServer;Lnet/minecraft/class_3218;Lcom/mojang/authlib/GameProfile;Lnet/minecraft/class_3225;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V [INJECT Applicator Phase -> sax.mixins.json:server.DeObfuscateTargetedBlock -> Apply Injections ->  -> Inject -> sax.mixins.json:server.DeObfuscateTargetedBlock->@Inject::initializeDeObfuscator(Lnet/minecraft/server/MinecraftServer;Lnet/minecraft/class_3218;Lcom/mojang/authlib/GameProfile;Lnet/minecraft/class_3225;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Invalid descriptor on sax.mixins.json:server.DeObfuscateTargetedBlock->@Inject::initializeDeObfuscator(Lnet/minecraft/server/MinecraftServer;Lnet/minecraft/class_3218;Lcom/mojang/authlib/GameProfile;Lnet/minecraft/class_3225;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V! Expected (Lnet/minecraft/server/MinecraftServer;Lnet/minecraft/class_3218;Lcom/mojang/authlib/GameProfile;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V but found (Lnet/minecraft/server/MinecraftServer;Lnet/minecraft/class_3218;Lcom/mojang/authlib/GameProfile;Lnet/minecraft/class_3225;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V [INJECT Applicator Phase -> sax.mixins.json:server.DeObfuscateTargetedBlock -> Apply Injections ->  -> Inject -> sax.mixins.json:server.DeObfuscateTargetedBlock->@Inject::initializeDeObfuscator(Lnet/minecraft/server/MinecraftServer;Lnet/minecraft/class_3218;Lcom/mojang/authlib/GameProfile;Lnet/minecraft/class_3225;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:517) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:447) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:385) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1284) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_262]
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_262]
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975) ~[?:1.8.0_262]
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000) ~[?:1.8.0_262]
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394) ~[?:1.8.0_262]
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750) ~[?:1.8.0_262]
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477) ~[?:1.8.0_262]
	at net.minecraft.class_1299.<clinit>(class_1299.java:176) ~[intermediary-server.jar:?]
	at net.minecraft.class_3103.<clinit>(class_3103.java:27) ~[intermediary-server.jar:?]
	at net.minecraft.class_3031.<clinit>(class_3031.java:67) ~[intermediary-server.jar:?]
	at net.minecraft.class_5464.<clinit>(class_5464.java:151) ~[intermediary-server.jar:?]
	at net.minecraft.class_5458.method_30571(class_5458.java:46) ~[intermediary-server.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:75) ~[intermediary-server.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) [?:1.8.0_262]
	at net.minecraft.class_5458.<clinit>(class_5458.java:74) [intermediary-server.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:255) [intermediary-server.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:43) [intermediary-server.jar:?]
	at net.minecraft.server.Main.main(Main.java:88) [intermediary-server.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_262]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27) [fabric-server-launch.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_262]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_262]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_262]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_262]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-server-launch.jar:?]

```

**Comment by Haven-King** [comment]
Old issue.
